name: Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          registry-url: "https://registry.npmjs.org"

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v5

      - name: Lint Code
        run: npm run lint

      - name: Typecheck Code
        run: npm run type:check

      - name: Test Code
        run: npm run test

      - name: Build Code
        run: npm run build